AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: s3://lambda-artifacts-f3abc8f375d85931/8976fa5a3ee209909f10f24a7221ba09
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 5
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_FullAccess
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
