AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: s3://lambda-artifacts-4f18e7ab318bf38a/048b686f2300fc2a748d75570227854d
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 5
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_FullAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
